core/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

from . import views
from .views import (
    atletas, dashboard, deletar_treino, editar_treino, index, resultados, treinos_list,
    user, create_treino, login_view, provas, presenca, novo_usuario, resultado,
    create, view, edit, update, delete_prova, create_resultado, error_404, error_500
)

# Custom error handlers
handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

urlpatterns = [
    path('index/', login_required(index), name='index'),
    path('user/', login_required(user), name='user'),

    # URL para a view de login
    path('', login_view, name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('novo_usuario/', login_required(novo_usuario), name='novo_usuario'),

    # Páginas Principais
    path('index/', index, name='index'),
    path('user/', user, name='user'),

    # Dashboard e Atletas
    path('dashboard/', login_required(dashboard), name='dashboard'),
    path('atletas/', login_required(atletas), name='atletas'),

    # Gestão de Treinos
    path('treinos/', login_required(treinos_list), name='treinos'),
    path('treinos/create/', login_required(create_treino), name='create_treino'),
    path('treinos/editar/<int:treino_id>/', login_required(editar_treino), name='editar_treino'),
    path('treinos/deletar/<int:treino_id>/', login_required(deletar_treino), name='deletar_treino'),

    # Gestão de Provas
    path('provas/', login_required(provas), name='provas'),
    path('provas/create/', login_required(create), name='create_prova'),
    path('provas/<int:pk>/', login_required(view), name='view_prova'),
    path('provas/<int:pk>/edit/', login_required(edit), name='edit_prova'),
    path('provas/<int:pk>/update/', login_required(update), name='update_prova'),
    path('delete_prova/', login_required(delete_prova), name='delete_prova'),

    # Resultados e Presença
    path('resultados/', login_required(resultados), name='resultados'),
    path('presenca/', login_required(presenca), name='presenca'),
    path('resultado/', login_required(resultado), name='resultado'),
    path('provas/create_resultado/', login_required(create_resultado), name='create_resultado'),
]

sgan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

from django.core.validators import RegexValidator #para o atributo fone, cpf 

# Define um validador personalizado para aceitar apenas dígitos e ter 11 caracteres
phone_validator = RegexValidator(
    regex=r'^\d{11}$',
    message="O número de celular deve conter exatamente 11 dígitos.",
)
# Define um validador para o formato de CPF (xxx.xxx.xxx-xx)
cpf_validator = RegexValidator(
    regex=r'^\d{3}\.\d{3}\.\d{3}-\d{2}$',
    message="O CPF deve estar no formato xxx.xxx.xxx-xx",
)
# Define um validador para o formato de MATRICULA (xxxxxxxx)
matricula_validator = RegexValidator(
    regex=r'^\d{8}$',
    message="Informe sua matrícula com 8 dígitos.",
)

### para as configurações BD do admin do django
class UsuarioManager(BaseUserManager):
    use_in_migrations=True
    #informamos que esse vai ser o model de user que vamos usar no BD para autentificação

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('O e-mail é obrigatório!')
        email = self.normalize_email(email)
        user = self.model(email=email, username=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        # nos campos que vierem no **extra_fields, podemos garantir que o campo 'is_superuser' seja falso.
        extra_fields.setdefault('is_superuser', False)
        # nos campos que vierem no **extra_fields, podemos garantir que o campo 'is_staff' seja verdadeiro.
        # extra_fields.setdefault('is_staff', True)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Super usuário precisa ter is_superuser=True')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Super usuário precisa ter is_staff=True')

        return self._create_user(email, password, **extra_fields)
#


class ModelUsuario(AbstractUser):
    email=models.EmailField('E-mail', unique=True) # usar email para fazer o login
    fone=models.CharField(
        max_length=11,
        validators=[phone_validator],
        blank=True,
        verbose_name="Número de celular",
        help_text="Somente números (DDD + 9 dígitos)",
    )
    is_staff=models.BooleanField('Treinador', default=True)
    #meus incrmentos 31/10/2023
    data_nascimento = models.DateField(null=True)
    SEXO_CHOICES = (
        ('F', 'Feminino'),
        ('M', 'Masculino'),
        ('O', 'Outros'),
    )

    sexo = models.CharField(
        max_length=1,
        choices=SEXO_CHOICES,
        verbose_name="Sexo",
        help_text="Selecione o sexo: Feminino, Masculino ou Outros",
    )
    cpf = models.CharField(
        max_length=14,  # Com traços e pontos, o máximo é 14 caracteres
        unique=True,
        validators=[cpf_validator],
        verbose_name="CPF",
        help_text="Informe seu CPF no formato xxx.xxx.xxx-xx",
    )
    endereco = models.CharField(max_length=100)
    
    curso = models.CharField(max_length=100)
    #curso = models.CharField(max_length=100, blank=True, verbose_name="Curso")


    matricula =models.CharField(
        max_length=8,
        unique=True,
        blank=True, 
        null=True,
        validators=[matricula_validator],
        verbose_name="Matrícula",
        help_text="Informe sua matrícula com 8 dígitos.",
    )
    
    socio = models.BooleanField('Sócio do Grêmio Fronteira', default=True)
    

     

    USERNAME_FIELD='email'      #poderiamos definir qualquer outro campo como username
    REQUIRED_FIELDS=['first_name', 'last_name', 'fone','data_nascimento','sexo', 'cpf','endereco','curso', 'matricula', 'socio']
    #campos email e senha não precisa informar, pois o Django sabe que eles são obrigatorios para a estrutura 

    def __str__(self):
        return self.email


    objects = UsuarioManager()#com isso especificicamos parao django usar o noss manager e não o padrao
    

class Treino(models.Model):
    # Campos do modelo Treino
    descricao = models.CharField(max_length=1000)


class DescricaoTreino(models.Model):
    treino = models.ForeignKey(Treino, on_delete=models.CASCADE, null = True)
    modelusuario = models.ForeignKey(ModelUsuario, on_delete=models.CASCADE, null = True)
    PSE_treinador = models.IntegerField(null = True)
    PSE_atleta = models.IntegerField(null = True)
    presenca = models.BooleanField(null = True)
    data_treino = models.DateField(null = True)
    distancia_total = models.IntegerField(null = True)

class Prova(models.Model):
    # Campos do modelo Prova (adapte de acordo com suas necessidades)
    nome_prova = models.CharField(max_length=50)
    distancia = models.DecimalField(max_digits=7, decimal_places=2)  
    estilo = models.CharField(max_length=25)
    naipe = models.CharField(max_length=20)
    
class Resultado(models.Model):
    modelusuario = models.ForeignKey(ModelUsuario, on_delete=models.CASCADE)
    prova = models.ForeignKey(Prova, on_delete=models.CASCADE)
    # Outros campos específicos do relacionamento 'resultado'
    tempo = models.DurationField()# exemplo de armazenamento de dados "00:02:30", "01:30:45.000500" vai armazenando de "HH:MM:SS.ssssss" (horas, minutos, segundos e microssegundos).
    classificacao = models.PositiveIntegerField()  # Campo para armazenar a classificação como número inteiro
    data_prova = models.DateField()

core/forms.py
from multiprocessing import AuthenticationError
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django import forms
from .models import DescricaoTreino, ModelUsuario, Treino, Prova, Resultado
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm

from django.utils.dateparse import parse_duration
from datetime import timedelta
from dateutil.parser import parse
from datetime import datetime, timedelta

class ModelUsuarioCreateForm(UserCreationForm):

    class Meta:
        model=ModelUsuario
        fields=('first_name', 'last_name','fone','data_nascimento','sexo', 'cpf','endereco','curso', 'matricula', 'socio')
        labels={'username': 'Username/E-mail'}

    def save(self, commit=True):
        user=super().save(commit=False) #commit=False faz salvar na variavel, mas não grava no BD
        user.set_password(self.cleaned_data["password1"]) #seta a senha
        user.email=self.cleaned_data['username'] #seta o username no campo de email
        


        if commit:
            user.save()
            
        return user

class ModelUsuarioChangeForm(UserChangeForm):
    class Meta:
        model=ModelUsuario
        fields=('first_name', 'last_name', 'fone','data_nascimento','sexo', 'cpf','endereco','curso', 'matricula', 'socio')

User = get_user_model()
class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(label="Email", max_length=254)

    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'autofocus': True})

    def confirm_login_allowed(self, user):
        super().confirm_login_allowed(user)

    def clean_username(self):
        username = self.cleaned_data['username']
        return User.objects.normalize_email(username)
    
class TreinoForm(forms.ModelForm):
    class Meta:
        model = Treino
        fields = ['descricao']  # Inclua apenas os campos que existem no modelo Treino

class DescricaoTreinoForm(forms.ModelForm):
    class Meta:
        model = DescricaoTreino
        exclude = ['treino']  # Exclui o campo treino do formulário, pois ele será definido na view
        fields = ['treino', 'PSE_treinador', 'data_treino']


# PARA PROVAS  
class ProvaForm(forms.ModelForm):
    class Meta:
        model = Prova
        #fields = ['nome_prova', 'estilo']
        fields = ['nome_prova', 'distancia', 'estilo', 'naipe']

    def save(self, commit=True):
        # Verifique se os dados estão sendo manipulados corretamente
        instancia_prova = super().save(commit=False)
        instancia_prova.distancia = self.cleaned_data['distancia']
        instancia_prova.naipe = self.cleaned_data['naipe']
        
        if commit:
            instancia_prova.save()
        return instancia_prova

#PARA RESULTADOS
class ResultadoForm(forms.ModelForm):
    class Meta:
        model = Resultado
        fields = ['modelusuario', 'prova', 'tempo', 'classificacao', 'data_prova']

    def clean_tempo(self):
        tempo = self.cleaned_data['tempo']

        try:
            # Verifique se já é um objeto timedelta
            if isinstance(tempo, timedelta):
                return tempo

            # Converta a string de tempo em um objeto timedelta
            tempo_timedelta = timedelta(seconds=float(tempo))
        except ValueError:
            raise forms.ValidationError("Formato de tempo inválido. Use HH:MM:SS.ssssss")

        return tempo_timedelta

    def save(self, commit=True):
        instancia_resultado = super().save(commit=False)
        instancia_resultado.tempo = self.cleaned_data['tempo']
        instancia_resultado.classificacao = self.cleaned_data['classificacao']
        
        if commit:
            instancia_resultado.save()
        return instancia_resultado
    

#PARA PAGINA DE ATLETAS

core/templates/atletas.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Atletas{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/sidebar.js' %}" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" crossorigin="anonymous">

    {% block extra_head %}
    {% endblock %}
</head>
<body>
    {% include 'sidebar.html' %}
    {% include 'header.html' %}
    <div class="center-content"> 
        {% block content %}
            <div class="container mt-4">
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                        <!-- Conteúdo para treinadores -->
                        <h2 class="mb-4">Buscar Atletas</h2>
                        <form method="GET" action="{% url 'atletas' %}" id="form-busca-atleta">
                            <div class="form-group">
                                <label for="id_modelusuario">Usuário:</label>
                                <select class="custom-select" name="modelusuario" id="id_modelusuario" required>
                                    {% for usuario in modelusuarios_list %}
                                        <option value="{{ usuario.pk }}">{{ usuario.first_name }} {{ usuario.last_name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <button type="button" class="btn btn-primary" onclick="exibirDetalhesAtleta()">Buscar</button>
                        </form>

                        <div id="dados-atletas" class="mt-4">
                            <!-- Exibir os dados do atleta selecionado -->
                            {% for usuario in modelusuarios_list %}
                                <div class="detalhes-atleta" id="atleta-{{ usuario.pk }}" style="display: none;">
                                    <h2>Detalhes do Atleta</h2>
                                    <p><strong>Email:</strong> {{ usuario.email }}</p>
                                    <p><strong>Nome:</strong> {{ usuario.get_full_name }}</p>
                                    <p><strong>Data de Nascimento:</strong> {{ usuario.data_nascimento }}</p>
                                    <p><strong>Sexo:</strong> {{ usuario.get_sexo_display }}</p>
                                    <p><strong>CPF:</strong> {{ usuario.cpf }}</p>
                                    <p><strong>Endereço:</strong> {{ usuario.endereco }}</p>
                                    <p><strong>Curso:</strong> {{ usuario.curso }}</p>
                                    <p><strong>Matrícula:</strong> {{ usuario.matricula }}</p>
                                    <p><strong>Sócio do Grêmio Fronteira:</strong> {% if usuario.socio %}Sim{% else %}Não{% endif %}</p>
                                    <p><strong>Participação:</strong> Atleta</p>
                                </div>
                            {% endfor %}
                        </div>

                    {% else %}
                        <!-- Conteúdo para atletas -->
                        <h2 class="mb-4">Meus Dados</h2>
                        <p><strong>Email:</strong> {{ user.email }}</p>
                        <p><strong>Nome:</strong> {{ user.get_full_name }}</p>
                        <p><strong>Data de Nascimento:</strong> {{ user.data_nascimento }}</p>
                        <p><strong>Sexo:</strong> {{ user.get_sexo_display }}</p>
                        <p><strong>CPF:</strong> {{ user.cpf }}</p>
                        <p><strong>Endereço:</strong> {{ user.endereco }}</p>
                        <p><strong>Curso:</strong> {{ user.curso }}</p>
                        <p><strong>Matrícula:</strong> {{ user.matricula }}</p>
                        <p><strong>Sócio do Grêmio Fronteira:</strong> {% if user.socio %}Sim{% else %}Não{% endif %}</p>
                        <p><strong>Participação:</strong> Atleta</p>
                    {% endif %}
                {% else %}
                    <!-- Mensagem para usuários não autenticados -->
                    <p>Você não está autenticado.</p>
                {% endif %}
            
            </div>
                       
        {% endblock %}      
    </div> 
    
    <!-- Bootstrap JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> 
    <script>
        function exibirDetalhesAtleta() {
            var form = document.getElementById('form-busca-atleta');
            var atletaId = form.querySelector('#id_modelusuario').value;

            if (!atletaId) {
                alert("Selecione um atleta antes de buscar.");
                return;
            }

            // Esconder todos os detalhes dos atletas
            var detalhesAtletas = document.querySelectorAll('.detalhes-atleta');
            detalhesAtletas.forEach(function(detalhes) {
                detalhes.style.display = 'none';
            });

            // Exibir detalhes do atleta selecionado
            var atletaSelecionado = document.getElementById('atleta-' + atletaId);
            if (atletaSelecionado) {
                atletaSelecionado.style.display = 'block';
            }
        }
    </script>
</body>
</html>

core/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Dashboard{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/sidebar.js' %}" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" crossorigin="anonymous">

    {% block extra_head %}
    {% endblock %}
</head>
<body>
    {% include 'sidebar.html' %}
    {% include 'header.html' %}
    <div class="center-content"> 
        {% block content %}
            <div class="container d-flex justify-content-center align-items-center" style="height: 100%;">
                {% include 'in-development.html' %}
            </div>
        {% endblock %}      
    </div>   
</body>
</html>

core/templates/header.html
<header>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-HJl5YYNq8FkIWp1MT5vZu6m80uMl2UtdnfbPzfaZL8r5IQq0y7duPeNfKgX5K7VI" crossorigin="anonymous">

    <div class="header-container">
        <h1>{{ titulo_pagina }}</h1>      
    </div>
    
    {% if user.is_authenticated %}
        <div class="user-info">
            <i class="fas fa-user user-icon " ></i>
            <span id="welcome-message" class="username">
                Bem-vindo, {% if user.is_staff %}Treinador(a){% else %}Atleta{% endif %}: {{ user.get_full_name|default:user.username }}
            </span>
        </div>
    {% endif %}
    
    <div class="header-icons">
        <a href="{% url 'dashboard' %}" class="home-link" title="Dashboard">
            <i class="fas fa-home"></i>
        </a>
        <a class="logout-button" href="{% url 'logout' %}">
            <i class="fas fa-sign-out-alt logout-icon"></i>
            Logout
        </a>
    </div>
</header>

core/templates/in-development.html
<!-- templates/in-development.html -->
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12 text-center">
            <i class="fas fa-cogs fa-5x mb-4"></i>
            <h1 class="h3 mb-3 font-weight-normal">Página em Desenvolvimento</h1>
            <p>Estamos trabalhando para melhorar esta página. Volte em breve!</p>
        </div>
    </div>
</div>

core/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>SGAN - Index</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/sidebar.js' %}" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" crossorigin="anonymous">
</head>
<body>
    {% include 'header.html' %}
    {% include 'sidebar.html' %}
    <div class="center-content">
        <center>
            <h1>SGAN</h1>
            <p>Sistema de Gerenciamento de Atletas e Natação</p>
        </center>
    </div>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

core/templates/login.html
<!-- templates/login.html -->
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login - SGAN</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>
<body>
  <!-- Toast para mensagens de erro -->
  <div id="errorToast" class="toast align-items-center text-white bg-danger border-0" role="alert" aria-live="assertive" aria-atomic="true" style="position: absolute; top: 20px; right: 20px;">
    <div class="d-flex">
      <div class="toast-body">
        Usuário ou senha incorretos.
      </div>
      <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>

  <div class="container">
    <div class="login-container">
      <!-- Título da página de login -->
      <h1 class="login-title">SGAN</h1>
      <div class="logo">
        <img src="{% static 'img/brasao_UFSC_vertical_sigla_fundo_escuro.png' %}" alt="UFSC Logo">
        <img src="{% static 'img/logo.png' %}" alt="AAACA Logo">
        <img src="{% static 'img/LOGO-GREMIO-NEW.png' %}" alt="Grêmio Fronteira Logo">
      </div>
      <form method="post" class="form-login">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Email" required class="form-control">
        <input type="password" name="password" placeholder="Password" required class="form-control">
        <button type="submit" class="btn btn-primary">Log In</button>
        <a href="{% url 'password_reset' %}" class="forgot-password">Esqueci minha senha</a>
      </form>
    </div>
  </div>

  <script>
    window.addEventListener('DOMContentLoaded', (event) => {
      // Verifica se há alguma mensagem de erro para exibir
      {% if messages %}
        var showToast = true;
      {% else %}
        var showToast = false;
      {% endif %}
  
      // Se showToast for true, exibe o toast
      if (showToast) {
        var toastElement = new bootstrap.Toast(document.getElementById('errorToast'));
        toastElement.show();
      }
    });
  </script>  
</body>
</html>

core/templates/novo-usuario.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Frase Simples</title>
</head>
<body>

    <h1>novo usuario!</h1>

</body>
</html>

core/templates/presenca.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Presença{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/sidebar.js' %}" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" crossorigin="anonymous">


    {% block extra_head %}
    {% endblock %}
</head>
<body>
    {% include 'sidebar.html' %}
    {% include 'header.html' %}
    <div class="center-content"> 
        {% block content %}
            <div class="container d-flex justify-content-center align-items-center" style="height: 100%;">
                {% include 'in-development.html' %}
            </div>
        {% endblock %}      
    </div> 
</body>
</html>

core/templates/resultados.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Resultados{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/sidebar.js' %}" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" crossorigin="anonymous">

    {% block extra_head %}
    {% endblock %}
</head>
<body>
    {% include 'sidebar.html' %}
    {% include 'header.html' %}
    <div class="center-content"> 
        {% block content %}
            <div class="container d-flex justify-content-center align-items-center" style="height: 100%;">
                {% include 'in-development.html' %}
            </div>
        {% endblock %}      
    </div> 
</body>
</html>

core/templates/sidebar.html
<!-- sidebar.html -->

<aside class="sidebar">
  <nav class="menu">
    <ul>
      <li>
        <a href="{% url 'dashboard' %}"
          ><i class="fas fa-tachometer-alt icon"></i
          ><span class="link-text">Visão Geral</span></a
        >
      </li>
      <li>
        <a href="{% url 'atletas' %}"
          ><i class="fas fa-running icon"></i
          ><span class="link-text">Atletas</span></a
        >
      </li>
      <li>
        <a href="{% url 'treinos' %}"
          ><i class="fas fa-stopwatch icon"></i
          ><span class="link-text">Treinos</span></a
        >
      </li>
      <li>
        <a href="{% url 'resultados' %}"
          ><i class="fas fa-chart-line icon"></i
          ><span class="link-text">Resultados</span></a
        >
      </li>
      <li>
        <a href="{% url 'provas' %}">
          <i class="fas fa-award icon"></i>
          <span class="link-text">Provas</span>
        </a>
      </li>
      <li>
        <a href="{% url 'presenca' %}">
          <i class="fas fa-user-check icon"></i>
          <span class="link-text">Presença</span>
        </a>
      </li>

      {% if user.is_staff %}
      <li>
        <a href="{% url 'novo_usuario' %}">
          <i class="fas fa-user-plus icon"></i>
          <span class="link-text">Novo Usuário</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>
</aside>
<button class="sidebar-toggle">
  <i class="fas fa-arrow-left"></i>
  <!--<span>Menu</span> Envolve o texto do menu em um span para esconder quando recolhido -->
</button>

core/templates/user.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Django 1 - Usuário</title>
</head>
<body>
    <h1>Usuário</h1>
</body>
</html>